version: '3.8'

services:
  # Core Module 1: Memory Core
  memory-core:
    image: node:18-alpine
    volumes:
      - ./1_memory-core:/app/1_memory-core
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
    working_dir: /app
    command: sh -c "echo 'Memory Core module ready' && tail -f /dev/null"
    networks:
      - asecn-network

  # Core Module 2: Perception Layer
  perception-layer:
    image: node:18-alpine
    volumes:
      - ./2_perception-layer:/app/2_perception-layer
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
    working_dir: /app
    command: sh -c "echo 'Perception Layer module ready' && tail -f /dev/null"
    depends_on:
      - memory-core
    networks:
      - asecn-network

  # Core Module 3: Action Layer
  action-layer:
    image: node:18-alpine
    volumes:
      - ./3_action-layer:/app/3_action-layer
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
    working_dir: /app
    command: sh -c "echo 'Action Layer module ready' && tail -f /dev/null"
    depends_on:
      - memory-core
      - perception-layer
    networks:
      - asecn-network

  # Core Module 4: Boot Task
  boot-task:
    image: node:18-alpine
    volumes:
      - ./4_boot-task:/app/4_boot-task
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
    working_dir: /app
    command: sh -c "echo 'Boot Task module ready' && tail -f /dev/null"
    depends_on:
      - memory-core
      - action-layer
    networks:
      - asecn-network

  # Core Module 5: Treasury
  treasury:
    image: node:18-alpine
    volumes:
      - ./5_treasury:/app/5_treasury
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
    working_dir: /app
    command: sh -c "echo 'Treasury module ready' && tail -f /dev/null"
    depends_on:
      - action-layer
    networks:
      - asecn-network

  # Core Module 6: Evolver
  evolver:
    image: node:18-alpine
    volumes:
      - ./6_evolver:/app/6_evolver
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
    working_dir: /app
    command: sh -c "echo 'Evolver module ready' && tail -f /dev/null"
    depends_on:
      - memory-core
    networks:
      - asecn-network

  # Support Module 1: Interfaces
  interfaces:
    image: node:18-alpine
    volumes:
      - ./7_interfaces:/app/7_interfaces
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
    working_dir: /app
    ports:
      - "3000:3000"  # Exposing port for web interface
    command: sh -c "echo 'Interfaces module ready' && tail -f /dev/null"
    depends_on:
      - memory-core
      - action-layer
    networks:
      - asecn-network

  # Support Module 2: Utilities & Tests
  utilities:
    image: node:18-alpine
    volumes:
      - ./8_utilities:/app/8_utilities
      - ./9_tests:/app/9_tests
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
    working_dir: /app
    command: sh -c "echo 'Utilities module ready' && tail -f /dev/null"
    networks:
      - asecn-network

networks:
  asecn-network:
    driver: bridge